export interface HadithBook {
  id: string;
  name: string;
  nameAr: string;
  nameUr: string;
  author: string;
  authorUr: string;
  hadithCount: number;
  volumes: number;
  category: 'kutub-sitta' | 'major' | 'other';
  icon: string;
  color: string;
  description: string;
  descriptionUr: string;
}

export interface TafseerBook {
  id: string;
  name: string;
  nameAr: string;
  nameUr: string;
  author: string;
  authorUr: string;
  volumes: number;
  language: string;
  icon: string;
  color: string;
  description: string;
  descriptionUr: string;
}

export interface IslamicBook {
  id: string;
  name: string;
  nameUr: string;
  author: string;
  authorUr: string;
  category: string;
  categoryUr: string;
  language: string;
  icon: string;
  color: string;
  description: string;
  descriptionUr: string;
}

export const KUTUB_SITTA: HadithBook[] = [
  {
    id: 'bukhari',
    name: 'Sahih Al-Bukhari',
    nameAr: 'صحيح البخاري',
    nameUr: 'صحیح البخاری',
    author: 'Imam Muhammad ibn Ismail Al-Bukhari',
    authorUr: 'امام محمد بن اسماعیل البخاری رحمہ اللہ',
    hadithCount: 7563,
    volumes: 9,
    category: 'kutub-sitta',
    icon: '📗',
    color: '#15803d',
    description: 'The most authentic book of Hadith after the Quran. Compiled by Imam Bukhari (194-256 AH).',
    descriptionUr: 'قرآن کریم کے بعد سب سے مستند حدیث کی کتاب۔ امام بخاری رحمہ اللہ (194-256 ہجری) کی تالیف۔',
  },
  {
    id: 'muslim',
    name: 'Sahih Muslim',
    nameAr: 'صحيح مسلم',
    nameUr: 'صحیح مسلم',
    author: 'Imam Muslim ibn al-Hajjaj',
    authorUr: 'امام مسلم بن الحجاج رحمہ اللہ',
    hadithCount: 7500,
    volumes: 5,
    category: 'kutub-sitta',
    icon: '📘',
    color: '#1d4ed8',
    description: 'Second most authentic Hadith collection. Known for its unique arrangement. Compiled 206-261 AH.',
    descriptionUr: 'دوسری سب سے مستند حدیث مجموعہ۔ اپنی منفرد ترتیب کے لیے مشہور۔ 206-261 ہجری میں مرتب۔',
  },
  {
    id: 'tirmidhi',
    name: 'Jami At-Tirmidhi',
    nameAr: 'جامع الترمذي',
    nameUr: 'جامع الترمذی',
    author: 'Imam Muhammad ibn Isa At-Tirmidhi',
    authorUr: 'امام محمد بن عیسیٰ الترمذی رحمہ اللہ',
    hadithCount: 3956,
    volumes: 6,
    category: 'kutub-sitta',
    icon: '📙',
    color: '#c2410c',
    description: 'Contains grade classifications for each hadith. A valuable reference for Islamic jurisprudence.',
    descriptionUr: 'ہر حدیث کا درجہ بندی کا نظام موجود۔ فقہ اسلامی کا قیمتی حوالہ۔',
  },
  {
    id: 'nasai',
    name: 'Sunan An-Nasai',
    nameAr: 'سنن النسائي',
    nameUr: 'سنن النسائی',
    author: 'Imam Ahmad ibn Shuayb An-Nasai',
    authorUr: 'امام احمد بن شعیب النسائی رحمہ اللہ',
    hadithCount: 5758,
    volumes: 8,
    category: 'kutub-sitta',
    icon: '📕',
    color: '#be123c',
    description: 'Known for detailed chain criticism. One of the most reliable after Bukhari and Muslim.',
    descriptionUr: 'سند کی تفصیلی تنقید کے لیے مشہور۔ بخاری اور مسلم کے بعد سب سے معتبر میں سے ایک۔',
  },
  {
    id: 'ibnmaja',
    name: 'Sunan Ibn Majah',
    nameAr: 'سنن ابن ماجه',
    nameUr: 'سنن ابن ماجہ',
    author: 'Imam Muhammad ibn Yazid ibn Majah',
    authorUr: 'امام محمد بن یزید بن ماجہ رحمہ اللہ',
    hadithCount: 4341,
    volumes: 5,
    category: 'kutub-sitta',
    icon: '📓',
    color: '#7c3aed',
    description: 'The sixth of the Kutub as-Sitta. Contains many hadiths not found in other major collections.',
    descriptionUr: 'کتب ستہ میں چھٹی کتاب۔ بہت سی احادیث جو دوسری مجموعوں میں نہیں ملتیں۔',
  },
  {
    id: 'abudawud',
    name: 'Sunan Abi Dawud',
    nameAr: 'سنن أبي داود',
    nameUr: 'سنن ابی داؤد',
    author: 'Imam Abu Dawud Sulayman ibn al-Ash\'ath',
    authorUr: 'امام ابو داؤد سلیمان بن اشعث رحمہ اللہ',
    hadithCount: 5274,
    volumes: 4,
    category: 'kutub-sitta',
    icon: '📒',
    color: '#0369a1',
    description: 'Focuses on legal and practice-oriented hadiths. Contains 5274 carefully selected ahadees.',
    descriptionUr: 'فقہی اور عملی احادیث پر توجہ۔ 5274 احتیاط سے منتخب احادیث پر مشتمل۔',
  },
];

export const OTHER_HADITH_BOOKS: HadithBook[] = [
  {
    id: 'muwatta',
    name: 'Al-Muwatta',
    nameAr: 'الموطأ',
    nameUr: 'موطا امام مالک',
    author: 'Imam Malik ibn Anas',
    authorUr: 'امام مالک بن انس رحمہ اللہ',
    hadithCount: 1720,
    volumes: 2,
    category: 'major',
    icon: '📜',
    color: '#0f766e',
    description: 'The earliest surviving hadith collection. Foundational text of Maliki jurisprudence.',
    descriptionUr: 'قدیم ترین محفوظ حدیث مجموعہ۔ مالکی فقہ کی بنیادی کتاب۔',
  },
  {
    id: 'musnad-ahmad',
    name: 'Musnad Ahmad',
    nameAr: 'مسند أحمد',
    nameUr: 'مسند احمد',
    author: 'Imam Ahmad ibn Hanbal',
    authorUr: 'امام احمد بن حنبل رحمہ اللہ',
    hadithCount: 40000,
    volumes: 50,
    category: 'major',
    icon: '📚',
    color: '#b45309',
    description: 'The largest collection with 40,000 hadiths. Arranged by narrator.',
    descriptionUr: '40,000 احادیث کے ساتھ سب سے بڑا مجموعہ۔ راویوں کے مطابق ترتیب۔',
  },
  {
    id: 'darimi',
    name: 'Sunan Ad-Darimi',
    nameAr: 'سنن الدارمي',
    nameUr: 'سنن الدارمی',
    author: 'Imam Abdullah ibn Abd al-Rahman Ad-Darimi',
    authorUr: 'امام عبداللہ بن عبدالرحمان الدارمی رحمہ اللہ',
    hadithCount: 3500,
    volumes: 2,
    category: 'major',
    icon: '📔',
    color: '#be185d',
    description: 'One of the important classical hadith collections arranged by legal subjects.',
    descriptionUr: 'فقہی موضوعات کے مطابق ترتیب دیا گیا اہم کلاسیکی حدیث مجموعہ۔',
  },
  {
    id: 'bayhaqi',
    name: 'Sunan Al-Bayhaqi',
    nameAr: 'سنن البيهقي',
    nameUr: 'سنن البیہقی',
    author: 'Imam Ahmad ibn al-Husayn Al-Bayhaqi',
    authorUr: 'امام احمد بن حسین البیہقی رحمہ اللہ',
    hadithCount: 21000,
    volumes: 10,
    category: 'major',
    icon: '🗂️',
    color: '#7c3aed',
    description: 'A comprehensive collection covering all aspects of Islamic law and practice.',
    descriptionUr: 'اسلامی قانون اور عمل کے تمام پہلوؤں کا جامع مجموعہ۔',
  },
  {
    id: 'mishkat',
    name: 'Mishkat Al-Masabih',
    nameAr: 'مشكاة المصابيح',
    nameUr: 'مشکاۃ المصابیح',
    author: 'Imam Khatib At-Tibrizi',
    authorUr: 'امام الخطیب التبریزی رحمہ اللہ',
    hadithCount: 6284,
    volumes: 3,
    category: 'major',
    icon: '🕯️',
    color: '#b45309',
    description: 'Popular compilation widely used in Islamic seminaries worldwide.',
    descriptionUr: 'دنیا بھر کے اسلامی مدارس میں بڑے پیمانے پر استعمال ہونے والا مشہور مجموعہ۔',
  },
  {
    id: 'riyadh',
    name: 'Riyadh As-Salihin',
    nameAr: 'رياض الصالحين',
    nameUr: 'ریاض الصالحین',
    author: 'Imam Yahya ibn Sharaf An-Nawawi',
    authorUr: 'امام یحیی بن شرف النووی رحمہ اللہ',
    hadithCount: 1896,
    volumes: 1,
    category: 'major',
    icon: '🌹',
    color: '#be123c',
    description: 'Gardens of the Righteous — a beloved collection of authentic hadiths on virtues.',
    descriptionUr: 'نیک لوگوں کے باغات — فضائل پر مستند احادیث کا محبوب مجموعہ۔',
  },
];

export const TAFSEER_BOOKS: TafseerBook[] = [
  {
    id: 'ibn-kathir',
    name: 'Tafseer Ibn Kathir',
    nameAr: 'تفسير ابن كثير',
    nameUr: 'تفسیر ابن کثیر',
    author: 'Imam Ismail ibn Kathir',
    authorUr: 'امام اسماعیل بن کثیر رحمہ اللہ',
    volumes: 10,
    language: 'Arabic/Urdu/English',
    icon: '📗',
    color: '#15803d',
    description: 'The most widely read and referenced Quran commentary. Uses Hadith extensively.',
    descriptionUr: 'سب سے زیادہ پڑھی اور حوالہ دی جانے والی تفسیر۔ حدیث کا وسیع استعمال۔',
  },
  {
    id: 'israr-ahmad',
    name: 'Bayan ul Quran (Dr. Israr Ahmad)',
    nameAr: 'بيان القرآن',
    nameUr: 'بیان القرآن (ڈاکٹر اسرار احمد)',
    author: 'Dr. Israr Ahmad',
    authorUr: 'ڈاکٹر اسرار احمد رحمہ اللہ',
    volumes: 9,
    language: 'Urdu',
    icon: '🎤',
    color: '#1d4ed8',
    description: 'Comprehensive Urdu tafseer with modern scholarly approach and strong emphasis on Quran.',
    descriptionUr: 'جدید علمی نقطہ نظر کے ساتھ جامع اردو تفسیر اور قرآن پر مضبوط زور۔',
  },
  {
    id: 'jalalain',
    name: 'Tafseer Al-Jalalain',
    nameAr: 'تفسير الجلالين',
    nameUr: 'تفسیر جلالین',
    author: 'Jalaluddin Al-Mahalli & Jalaluddin As-Suyuti',
    authorUr: 'جلال الدین المحلی اور جلال الدین السیوطی رحمہما اللہ',
    volumes: 1,
    language: 'Arabic',
    icon: '✨',
    color: '#c2410c',
    description: 'Concise classical commentary. One of the most studied tafseer in Islamic seminaries.',
    descriptionUr: 'مختصر کلاسیکی تفسیر۔ اسلامی مدارس میں سب سے زیادہ پڑھی جانے والی تفسیروں میں سے ایک۔',
  },
  {
    id: 'tabari',
    name: 'Tafseer At-Tabari',
    nameAr: 'تفسير الطبري',
    nameUr: 'تفسیر الطبری',
    author: 'Imam Muhammad ibn Jarir At-Tabari',
    authorUr: 'امام محمد بن جریر الطبری رحمہ اللہ',
    volumes: 30,
    language: 'Arabic',
    icon: '📜',
    color: '#7c3aed',
    description: 'The monumental tafseer of 30 volumes. Invaluable source for Islamic scholarship.',
    descriptionUr: '30 جلدوں کی عظیم تفسیر۔ اسلامی علمیت کے لیے انمول ذریعہ۔',
  },
  {
    id: 'qurtubi',
    name: 'Tafseer Al-Qurtubi',
    nameAr: 'تفسير القرطبي',
    nameUr: 'تفسیر القرطبی',
    author: 'Imam Abu Abdallah Al-Qurtubi',
    authorUr: 'امام ابو عبداللہ القرطبی رحمہ اللہ',
    volumes: 20,
    language: 'Arabic',
    icon: '🏛️',
    color: '#be123c',
    description: 'Focuses on legal aspects of Quranic verses. Comprehensive and scholarly work.',
    descriptionUr: 'قرآنی آیات کے فقہی پہلوؤں پر توجہ۔ جامع اور علمی کام۔',
  },
  {
    id: 'maariful-quran',
    name: 'Maarif ul Quran',
    nameAr: 'معارف القرآن',
    nameUr: 'معارف القرآن',
    author: 'Mufti Muhammad Shafi Usmani',
    authorUr: 'مفتی محمد شفیع عثمانی رحمہ اللہ',
    volumes: 8,
    language: 'Urdu',
    icon: '🌙',
    color: '#0369a1',
    description: 'Comprehensive Urdu tafseer. Widely used in South Asian Islamic scholarship.',
    descriptionUr: 'جامع اردو تفسیر۔ جنوبی ایشیائی اسلامی علمیت میں وسیع پیمانے پر استعمال۔',
  },
  {
    id: 'tafheem',
    name: 'Tafheem ul Quran',
    nameAr: 'تفهيم القرآن',
    nameUr: 'تفہیم القرآن',
    author: 'Syed Abul Ala Maududi',
    authorUr: 'سید ابو الاعلیٰ مودودی رحمہ اللہ',
    volumes: 6,
    language: 'Urdu',
    icon: '🔍',
    color: '#b45309',
    description: 'Modern Urdu tafseer explaining Quran with social and political context.',
    descriptionUr: 'معاشرتی اور سیاسی سیاق و سباق کے ساتھ قرآن کی جدید اردو تفسیر۔',
  },
  {
    id: 'ruh-al-maani',
    name: 'Ruh Al-Maani',
    nameAr: 'روح المعاني',
    nameUr: 'روح المعانی',
    author: 'Imam Mahmoud Al-Alusi',
    authorUr: 'امام محمود الآلوسی رحمہ اللہ',
    volumes: 16,
    language: 'Arabic',
    icon: '💎',
    color: '#7c3aed',
    description: 'Encyclopedia of tafseer combining linguistic, mystical and legal approaches.',
    descriptionUr: 'لسانی، روحانی اور قانونی نقطہ ہائے نظر کو یکجا کرنے والا تفسیر کا انسائیکلوپیڈیا۔',
  },
];

export const SEERAH_BOOKS: IslamicBook[] = [
  {
    id: 'ibn-hisham',
    name: 'Seerah Ibn Hisham',
    nameUr: 'سیرت ابن ہشام',
    author: 'Imam Ibn Hisham',
    authorUr: 'امام ابن ہشام رحمہ اللہ',
    category: 'Seerah',
    categoryUr: 'سیرت',
    language: 'Arabic',
    icon: '🕌',
    color: '#15803d',
    description: 'The foundational classical biography of Prophet Muhammad ﷺ',
    descriptionUr: 'نبی کریم ﷺ کی بنیادی کلاسیکی سوانح حیات',
  },
  {
    id: 'sealed-nectar',
    name: 'Ar-Raheeq Al-Makhtum',
    nameUr: 'الرحیق المختوم',
    author: 'Sheikh Safiur Rahman Mubarakpuri',
    authorUr: 'شیخ صفی الرحمان مبارکپوری رحمہ اللہ',
    category: 'Seerah',
    categoryUr: 'سیرت',
    language: 'Arabic/Urdu/English',
    icon: '🏆',
    color: '#b45309',
    description: 'Award-winning Seerah book. Winner of the 1st Islamic Award in 1979.',
    descriptionUr: 'ایوارڈ یافتہ سیرت کتاب۔ 1979 میں پہلا اسلامی ایوارڈ جیتا۔',
  },
  {
    id: 'seerah-ibn-kathir',
    name: 'Al-Bidayah wan-Nihayah (Seerah)',
    nameUr: 'البدایہ والنہایہ',
    author: 'Imam Ibn Kathir',
    authorUr: 'امام ابن کثیر رحمہ اللہ',
    category: 'Seerah',
    categoryUr: 'سیرت',
    language: 'Arabic',
    icon: '📖',
    color: '#1d4ed8',
    description: 'Comprehensive history of Islam from creation to 14th century CE.',
    descriptionUr: 'تخلیق سے 14ویں صدی عیسوی تک اسلام کی جامع تاریخ۔',
  },
  {
    id: 'fazail-amaal',
    name: 'Fazail-e-Amaal',
    nameUr: 'فضائل اعمال',
    author: 'Sheikh Muhammad Zakariyya Kandhlawi',
    authorUr: 'شیخ محمد زکریا کاندھلوی رحمہ اللہ',
    category: 'Virtues',
    categoryUr: 'فضائل',
    language: 'Urdu',
    icon: '⭐',
    color: '#be123c',
    description: 'Virtues and excellence of Islamic practices. Widely read in Islamic circles.',
    descriptionUr: 'اسلامی اعمال کے فضائل اور اہمیت۔ اسلامی حلقوں میں بڑے پیمانے پر پڑھی جاتی ہے۔',
  },
];

export const OTHER_ISLAMIC_BOOKS: IslamicBook[] = [
  {
    id: 'ihya-ulum',
    name: 'Ihya Ulum Ad-Din',
    nameUr: 'احیاء علوم الدین',
    author: 'Imam Al-Ghazali',
    authorUr: 'امام الغزالی رحمہ اللہ',
    category: 'Spirituality',
    categoryUr: 'روحانیت',
    language: 'Arabic',
    icon: '💫',
    color: '#0f766e',
    description: 'The Revival of Religious Sciences. Masterpiece on Islamic ethics and spirituality.',
    descriptionUr: 'دینی علوم کا احیاء۔ اسلامی اخلاق اور روحانیت پر شاہکار۔',
  },
  {
    id: 'fiqh-us-sunnah',
    name: 'Fiqh Us-Sunnah',
    nameUr: 'فقہ السنہ',
    author: 'Sayyid Sabiq',
    authorUr: 'سید سابق رحمہ اللہ',
    category: 'Fiqh',
    categoryUr: 'فقہ',
    language: 'Arabic/English',
    icon: '⚖️',
    color: '#1d4ed8',
    description: 'Comprehensive guide to Islamic jurisprudence based on Quran and Sunnah.',
    descriptionUr: 'قرآن و سنت پر مبنی اسلامی فقہ کا جامع رہنما۔',
  },
  {
    id: 'bulugh-al-maram',
    name: 'Bulugh Al-Maram',
    nameUr: 'بلوغ المرام',
    author: 'Ibn Hajar Al-Asqalani',
    authorUr: 'ابن حجر العسقلانی رحمہ اللہ',
    category: 'Fiqh',
    categoryUr: 'فقہ',
    language: 'Arabic',
    icon: '📋',
    color: '#7c3aed',
    description: 'Ahadees related to Islamic law. Essential reference for Islamic jurisprudence.',
    descriptionUr: 'اسلامی قانون سے متعلق احادیث۔ اسلامی فقہ کا لازمی حوالہ۔',
  },
  {
    id: 'akhlaq-nabawi',
    name: 'Akhlaq an-Nabi ﷺ',
    nameUr: 'اخلاقِ نبوی ﷺ',
    author: 'Imam Abu Bakr Al-Ajuri',
    authorUr: 'امام ابو بکر الآجری رحمہ اللہ',
    category: 'Character',
    categoryUr: 'اخلاق',
    language: 'Arabic',
    icon: '🌟',
    color: '#b45309',
    description: 'The noble character and manners of Prophet Muhammad ﷺ',
    descriptionUr: 'نبی کریم ﷺ کا اعلیٰ اخلاق اور آداب',
  },
  {
    id: 'islamic-finance',
    name: 'Islamic Economics & Finance',
    nameUr: 'اسلامی معاشیات و مالیات',
    author: 'Various Scholars',
    authorUr: 'مختلف علماء',
    category: 'Economics',
    categoryUr: 'معاشیات',
    language: 'Urdu/English',
    icon: '💰',
    color: '#0369a1',
    description: 'Islamic principles of economics, trade, banking and financial ethics.',
    descriptionUr: 'معاشیات، تجارت، بینکاری اور مالی اخلاق کے اسلامی اصول۔',
  },
  {
    id: 'social-system',
    name: 'Social System of Islam',
    nameUr: 'اسلام کا نظامِ معاشرت',
    author: 'Various Scholars',
    authorUr: 'مختلف علماء',
    category: 'Social',
    categoryUr: 'معاشرت',
    language: 'Urdu/English',
    icon: '🤝',
    color: '#15803d',
    description: 'Islamic guidance on family, society, rights, and community values.',
    descriptionUr: 'خاندان، معاشرہ، حقوق اور اجتماعی اقدار پر اسلامی رہنمائی۔',
  },
  {
    id: 'political-islam',
    name: 'Islamic Political System',
    nameUr: 'اسلامی نظامِ سیاست',
    author: 'Various Scholars',
    authorUr: 'مختلف علماء',
    category: 'Politics',
    categoryUr: 'سیاست',
    language: 'Urdu/English',
    icon: '🏛️',
    color: '#be123c',
    description: 'Islamic principles of governance, justice, and political ethics.',
    descriptionUr: 'حکمرانی، انصاف اور سیاسی اخلاقیات کے اسلامی اصول۔',
  },
];
